language: php

dist: xenial

env:
    global:
        - SYMFONY_PHPUNIT_DISABLE_RESULT_CACHE=1

matrix:
    include:
        - php: 7.2
          #env:
          #  - SYMFONY_REQUIRE='^4.4'
        - php: 7.3
          env:
            - lint=1
            - QA_DOCKER_IMAGE=jakzal/phpqa:1.25.0-php7.3-alpine
          services:
              - docker
    fast_finish: true

sudo: false

cache:
    directories:
        - $HOME/.composer/cache/files

before_install:
    - phpenv config-rm xdebug.ini || echo "xdebug not available"
    - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - composer global require symfony/flex

    - if [[ $lint = 1 ]]; then docker pull ${QA_DOCKER_IMAGE}; fi
    - export PATH="$PATH:$HOME/.composer/vendor/bin"

install:
    - composer install --prefer-dist --no-progress --no-suggest --ansi

script:
    - vendor/bin/phpunit --verbose
    - |
        if [[ $lint = 1 ]]
        then
            mkdir /tmp/tmp-phpqa-$(id -u)
            export QA_DOCKER_COMMAND="docker run --init --interactive --tty --rm --user "$(id -u):$(id -g)" --volume /tmp/tmp-phpqa-$(id -u):/tmp --volume "$(pwd):/project" --workdir /project ${QA_DOCKER_IMAGE}"
            sh -c "${QA_DOCKER_COMMAND} php-cs-fixer fix -vvv --diff --dry-run"
            sh -c "${QA_DOCKER_COMMAND} phpstan analyse"
            #sh -c "${QA_DOCKER_COMMAND} vendor/bin/psalm --show-info=false"
        fi
